import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, Check, FileText, MapPin, Package, Printer, Truck, User, X, ShieldCheck } from 'lucide-react';
import { panel } from '@/api/services';
import { cn, formatDate, formatINR } from '@/lib/utils';
import { useDocumentTitle } from '@/hooks';
import { useUI } from '@/store/ui';
import { ORDER_LABEL, OrderStatusPill } from '@/components/common';
import { Button, Img, Modal, Radio, Select, Skeleton, Textarea, Input } from '@/components/ui';

export default function OrderDetailPage() {
  const { id } = useParams();
  const qc = useQueryClient();
  const toast = useUI((s) => s.toast);
  const { data: o } = useQuery({ queryKey: ['order', id], queryFn: () => panel.order(id!) });
  useDocumentTitle(o ? `Order ${o.number}` : 'Order');
  const [modal, setModal] = useState<'reject' | 'ship' | 'return' | null>(null);
  const [reason, setReason] = useState('');
  const [carrier, setCarrier] = useState('Delhivery');
  const [awb, setAwb] = useState('');
  const [retDecision, setRetDecision] = useState<'approve' | 'reject'>('approve');
  const act = useMutation({ mutationFn: (a: Parameters<typeof panel.orderAction>) => panel.orderAction(...a), onSuccess: (u, [, action]) => { qc.setQueryData(['order', id], u); qc.invalidateQueries({ queryKey: ['orders'] }); setModal(null); toast({ message: { CONFIRM: 'Order confirmed', REJECT: 'Order rejected and customer refunded', PACK: 'Marked as packed. Generate the label to ship.', SHIP: 'Pickup scheduled and customer notified', RETURN_APPROVE: 'Return approved, reverse pickup scheduled', RETURN_REJECT: 'Return declined', RETURN_REFUND: 'Refund issued' }[action], kind: 'success' }); } });
  if (!o) return <div className="space-y-4"><Skeleton className="h-8 w-64" /><Skeleton className="h-64 rounded-lg" /></div>;

  const next = o.status === 'NEW' ? { label: 'Confirm order', action: 'CONFIRM' as const, icon: Check } : o.status === 'CONFIRMED' ? { label: 'Mark as packed', action: 'PACK' as const, icon: Package } : o.status === 'PACKED' ? { label: 'Generate label and schedule pickup', action: null, icon: Truck } : null;
  const Row = ({ k, v }: { k: string; v: React.ReactNode }) => <div className="flex justify-between gap-4 py-1.5 text-body"><dt className="text-ink-500">{k}</dt><dd className="text-ink-900 tabular text-right">{v}</dd></div>;

  return (
    <div>
      <Link to="/orders" className="inline-flex items-center gap-1.5 text-body-sm text-ink-500 hover:text-ink-900 mb-3"><ArrowLeft className="h-4 w-4" /> Orders</Link>
      <div className="flex items-start justify-between gap-4 flex-wrap mb-5">
        <div><div className="flex items-center gap-3"><h1 className="font-display text-[26px] md:text-[30px] font-semibold text-ink-900 tabular">{o.number}</h1><OrderStatusPill s={o.status} /></div><p className="text-body text-ink-500 mt-1">Placed {formatDate(o.placedAt, { hour: '2-digit', minute: '2-digit' })}. {o.payment === 'COD' ? 'Cash on delivery' : 'Prepaid'}, {o.paymentStatus.toLowerCase()}.</p></div>
        <div className="flex gap-2 flex-wrap">
          {o.status !== 'CANCELLED' && <Button variant="outline" onClick={() => toast({ message: 'Invoice PDF is generated by the server', kind: 'info' })}><FileText className="h-4 w-4" /> Invoice</Button>}
          {['PACKED', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED'].includes(o.status) && <Button variant="outline" onClick={() => toast({ message: 'Shipping label PDF is generated by the server', kind: 'info' })}><Printer className="h-4 w-4" /> Label</Button>}
          {o.status === 'NEW' && <Button variant="ghost" onClick={() => setModal('reject')}><X className="h-4 w-4" /> Reject</Button>}
          {next && <Button onClick={() => (next.action ? act.mutate([o.id, next.action]) : setModal('ship'))} loading={act.isPending}><next.icon className="h-4 w-4" /> {next.label}</Button>}
          {o.status === 'RETURN_REQUESTED' && o.returnRequest?.status === 'REQUESTED' && <Button onClick={() => setModal('return')}>Respond to return</Button>}
          {o.status === 'RETURN_REQUESTED' && o.returnRequest?.status === 'APPROVED' && <Button onClick={() => act.mutate([o.id, 'RETURN_REFUND'])} loading={act.isPending}>Item received, issue refund</Button>}
        </div>
      </div>

      <div className="grid lg:grid-cols-[1fr_340px] gap-4 items-start">
        <div className="space-y-4">
          {o.returnRequest && (
            <section className="rounded-lg border border-warning-400 bg-warning-50 p-4"><div className="text-body font-semibold text-ink-900">Return request, {o.returnRequest.type.toLowerCase()}</div><div className="text-body-sm text-ink-700 mt-1"><b>{o.returnRequest.reason}</b>{o.returnRequest.note ? `: ${o.returnRequest.note}` : ''}</div><div className="text-caption text-ink-500 mt-1">Requested {formatDate(o.returnRequest.requestedAt)}. Status: {o.returnRequest.status.toLowerCase().replace('_', ' ')}. Respond within 48 hours.</div></section>
          )}
          <section className="rounded-lg bg-white border border-border-strong">
            <div className="px-4 py-3 border-b border-border-subtle text-h4 text-ink-900">Items</div>
            <ul className="divide-y divide-border-subtle">{o.items.map((it) => <li key={it.id} className="p-4 flex gap-4"><Img src={it.image} alt="" className="h-16 w-16 rounded-md object-cover bg-cream-200" /><div className="min-w-0 flex-1"><div className="text-body text-ink-900">{it.title}</div><div className="text-caption text-ink-500">{it.variant ? `${it.variant}, ` : ''}Qty {it.qty}</div>{it.authenticityCode && <div className="text-caption text-info-600 inline-flex items-center gap-1 mt-0.5"><ShieldCheck className="h-3.5 w-3.5" /> Code {it.authenticityCode}</div>}</div><div className="text-body font-semibold text-ink-900 tabular">{formatINR(it.qty * it.unitPrice)}</div></li>)}</ul>
          </section>
          <section className="rounded-lg bg-white border border-border-strong p-4">
            <h2 className="text-h4 text-ink-900 mb-3">Timeline</h2>
            <ol className="relative border-l-2 border-cream-300 ml-2 space-y-3">{[...o.timeline].reverse().map((t, i) => <li key={i} className="pl-4 relative"><span className={cn('absolute -left-[7px] top-1.5 h-3 w-3 rounded-full', i === 0 ? 'bg-accent-600' : 'bg-cream-300')} /><div className="text-body text-ink-900">{t.status === 'PICKUP_SCHEDULED' ? 'Pickup scheduled' : ORDER_LABEL[t.status]}</div>{t.note && <div className="text-body-sm text-ink-700">{t.note}</div>}<div className="text-caption text-ink-500">{formatDate(t.at, { hour: '2-digit', minute: '2-digit' })}</div></li>)}</ol>
          </section>
        </div>
        <div className="space-y-4">
          <section className="rounded-lg bg-white border border-border-strong p-4"><h2 className="text-h4 text-ink-900 mb-2 inline-flex items-center gap-2"><User className="h-4 w-4 text-ink-500" /> Customer</h2><div className="text-body text-ink-900">{o.customer.name}</div><div className="text-body-sm text-ink-700">{o.customer.phone}</div><div className="text-body-sm text-ink-700">{o.customer.email}</div></section>
          <section className="rounded-lg bg-white border border-border-strong p-4"><h2 className="text-h4 text-ink-900 mb-2 inline-flex items-center gap-2"><MapPin className="h-4 w-4 text-ink-500" /> Ship to</h2><div className="text-body-sm text-ink-700">{o.address.line1}{o.address.line2 ? `, ${o.address.line2}` : ''}<br />{o.address.city}, {o.address.state} {o.address.pincode}</div></section>
          {o.shipment && <section className="rounded-lg bg-white border border-border-strong p-4"><h2 className="text-h4 text-ink-900 mb-2 inline-flex items-center gap-2"><Truck className="h-4 w-4 text-ink-500" /> Shipment</h2><div className="text-body text-ink-900">{o.shipment.carrier}</div><div className="text-body-sm text-ink-700 tabular">AWB {o.shipment.awb}</div>{o.shipment.eta && <div className="text-caption text-ink-500">Expected {formatDate(o.shipment.eta)}</div>}</section>}
          <section className="rounded-lg bg-white border border-border-strong p-4"><h2 className="text-h4 text-ink-900 mb-1">Payment summary</h2><dl className="divide-y divide-border-subtle"><Row k="Items" v={formatINR(o.subtotal)} />{o.discount > 0 && <Row k="Discount" v={`- ${formatINR(o.discount)}`} />}<Row k="Shipping" v={o.shipping ? formatINR(o.shipping) : 'Free'} /><Row k="Order total" v={<b>{formatINR(o.total)}</b>} /><Row k="Platform commission" v={<span className="text-error-700">- {formatINR(o.commission)}</span>} /><Row k="Your earning" v={<b className="text-success-700">{formatINR(o.netEarning)}</b>} /></dl><p className="text-caption text-ink-500 mt-2">Available for payout 7 days after delivery.</p></section>
        </div>
      </div>

      <Modal open={modal === 'reject'} onClose={() => setModal(null)} title="Reject this order" footer={<div className="flex justify-end gap-3"><Button variant="ghost" onClick={() => setModal(null)}>Keep order</Button><Button variant="destructive" disabled={!reason} loading={act.isPending} onClick={() => act.mutate([o.id, 'REJECT', { reason }])}>Reject order</Button></div>}>
        <p className="text-body text-ink-700 mb-4">The customer will be refunded in full. Frequent rejections lower your seller rating.</p>
        <div className="space-y-3">{['Out of stock', 'Cannot ship to this pincode', 'Pricing error on listing', 'Other'].map((r) => <Radio key={r} name="rr" checked={reason === r} onChange={() => setReason(r)} label={r} />)}</div>
      </Modal>
      <Modal open={modal === 'ship'} onClose={() => setModal(null)} title="Ship this order" footer={<div className="flex justify-end gap-3"><Button variant="ghost" onClick={() => setModal(null)}>Cancel</Button><Button loading={act.isPending} onClick={() => act.mutate([o.id, 'SHIP', { carrier, awb }])}>Schedule pickup</Button></div>}>
        <div className="space-y-4">
          <Select label="Courier" value={carrier} onChange={(e) => setCarrier(e.target.value)}>{['Delhivery', 'Bluedart', 'DTDC', 'India Post', 'Self-ship'].map((c) => <option key={c}>{c}</option>)}</Select>
          {carrier === 'Self-ship' ? <Input label="Tracking number" value={awb} onChange={(e) => setAwb(e.target.value)} /> : <p className="text-body-sm text-ink-700">A pickup will be requested from {carrier} for tomorrow, and the label and manifest will be generated. The customer gets the tracking link automatically.</p>}
        </div>
      </Modal>
      <Modal open={modal === 'return'} onClose={() => setModal(null)} title="Respond to return request" footer={<div className="flex justify-end gap-3"><Button variant="ghost" onClick={() => setModal(null)}>Cancel</Button><Button variant={retDecision === 'approve' ? 'primary' : 'destructive'} disabled={retDecision === 'reject' && !reason} loading={act.isPending} onClick={() => act.mutate([o.id, retDecision === 'approve' ? 'RETURN_APPROVE' : 'RETURN_REJECT', { reason }])}>{retDecision === 'approve' ? 'Approve and schedule pickup' : 'Decline return'}</Button></div>}>
        <div className="space-y-3">
          <Radio name="rd" checked={retDecision === 'approve'} onChange={() => setRetDecision('approve')} label={<span><b>Approve.</b> Free reverse pickup is scheduled; refund after inspection.</span>} />
          <Radio name="rd" checked={retDecision === 'reject'} onChange={() => setRetDecision('reject')} label={<span><b>Decline.</b> Only for non-returnable items or requests outside the 7-day window. The customer may escalate.</span>} />
          {retDecision === 'reject' && <Textarea label="Reason shown to the customer" value={reason} onChange={(e) => setReason(e.target.value)} />}
        </div>
      </Modal>
    </div>
  );
}
